In [2]:
import torch
import numpy as np


In [3]:
scalar = torch.tensor(42)
vector = torch.tensor([1.0, 2.0, 3.0])
matrix = torch.tensor([[1, 2], [3, 4]])

In [4]:
scalar

tensor(42)

In [5]:
vector

tensor([1., 2., 3.])

In [6]:
matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
print(vector.shape, vector.dtype)
print(matrix.dtype)

torch.Size([3]) torch.float32
torch.int64


In [15]:
rand_weight = torch.randn(3, 4)
zeroes = torch.zeros(2,2)
ones = torch.ones(2,2)
eye = torch.eye(3)
arange = torch.arange(0, 10, step=2)
rand = torch.rand(2, 3)
lin = torch.linspace(0, 1, steps=5)

In [9]:
rand_weight

tensor([[ 1.7401,  0.6662, -0.6616,  0.6315],
        [ 0.7910,  0.2091, -1.5020,  0.0405],
        [ 0.3107,  0.0653, -0.9737,  0.0619]])

In [10]:
zeroes

tensor([[0., 0.],
        [0., 0.]])

In [11]:
ones

tensor([[1., 1.],
        [1., 1.]])

In [12]:
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
arange

tensor([0, 2, 4, 6, 8])

In [16]:
lin

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [17]:
rand

tensor([[0.2268, 0.7959, 0.4998],
        [0.3956, 0.6811, 0.7586]])

In [19]:
np_arr = np.array([1.0, 2.0, 3.0])
np_arr

array([1., 2., 3.])

In [21]:
t = torch.from_numpy(np_arr)
t

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
back = t.numpy()
back

array([1., 2., 3.])

In [24]:
t[0] = 99.0

In [25]:
np_arr

array([99.,  2.,  3.])

In [28]:
A = torch.tensor([[1.0,2.0] , [3.0,4.0]])
B= torch.tensor([[1.0,2.0],
                 [3.0,4.0]])

In [29]:
C = A@B
C

tensor([[ 7., 10.],
        [15., 22.]])

In [31]:
X = torch.tensor([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

print(X[0])
print(X[:, 1])
print(X[1:, :2])

tensor([10, 11, 12])
tensor([11, 21, 31])
tensor([[20, 21],
        [30, 31]])


In [32]:
x = torch.tensor([1, -2, 3, -4, 5])
mask = x > 0
print(mask)
print(x[mask])

tensor([ True, False,  True, False,  True])
tensor([1, 3, 5])
